### ISSUE TITLE
Can't connect to the socket from the React-native

### ISSUE THREAD

**Issue by romreed** [BitSharesEurope/docs.bitshares.eu#59]
Hello. I try to connect to the socket using the socket.io-client, but I get only the "SocketRocket: In debug mode. Allowing connection to any root cert." I checked different versions of the library and react-native and nothing happens. I thought that the address of the server is not correct but checked and it works as it should. I also created node js on localhost, connected to it and everything works, but does not connect to the remote server. 
url: wss://bitshares.openledger.info/ws
"socket.io-client": "2.0.4",
"react-native": "0.58.3".
Can you say me what library you use for work with socket and version.

**Comment by clockworkgr** [comment]
just use any standard websocket library.

Socket.io is NOT a pure websocket library. It utilises websockets too but is not a replacement for a websocket client.

I strongly suggest you use the bitsharesjs library instead of communicating directly on the websocket level with an API node.

See here: https://github.com/bitshares/bitsharesjs#readme
